### ISSUE TITLE
Reactivate live-py-output-buffer in its window

### ISSUE THREAD

**Issue by brandm** [donkirkby/live-py-plugin#100]
I stumbled upon this issue in Emacs (in all examples the active cursor is at `|`):

Starting from a live coding setup

```
# Python code:   # # live-py-output:
x = 1            # x = 1
|x += 2          # x = 3
```

change to the window on the right side and lookup some notes

```
# Python code:   # # file ~/my_notes.txt:
x = 1            # My notes line 42.
x += 2           # |My notes line 43.
```

and then go back to the window on the left side.

```
# Python code:   # # file ~/my_notes.txt:
x = 1            # My notes line 42.
|x += 2          # My notes line 43.
```

Now after `C-p` (`previous-line`) what happens is

```
# Python code:   # # file ~/my_notes.txt:
|x = 1           # My notes line 1.
x += 2           # My notes line 2.
```

messing up the scroll view of the buffer `~/my_notes.txt` but I would expect to be switched back to the live coding setup (like I would be when I would invoke `live-py-mode` freshly).

```
# Python code:   # # live-py-output:
|x = 1           # x = 1
x += 2           # x = 3
```

If my expectation above is right I would be happy to create my first pull request for the live-py-plugin. It would insert

```
(set-window-buffer live-py-output-window live-py-output-buffer)
```

before the `with-selected-window` form in `live-py-synchronize-scroll` for Emacs. For me it works, also with more than one `live-py-mode` sessions in the same Emacs frame.

I don't know if something similar would be necessary for the other supported editors and how to do it there and would therefore leave that out.

**Comment by donkirkby** [comment]
I've noticed similar problems, but the live coding display seems to come back when you edit the Python code.

However, if you want to create a pull request with an improvement, I will definitely try it out.

**Comment by brandm** [comment]
Good point, thanks. So I reduced my change to affect only `live-py-check-to-scroll`, not `live-py-trace` any more which does the display already on its own.

**Comment by brandm** [comment]
There are new (from my 6ee2429f) and old issues in Emacs with a few of some corner cases when the output buffer and/or output window is missing. They occur when `live-py-synchronize-scroll`, `live-py-trace`, disabling `live-py-mode` or killing the Python buffer is in use after killing the output buffer and/or reverting the `split-window-horizontally` for the output window.

Please review and let me know if a different pull request than the one submitted is desirable.

The temporary `live-py-mode.el` that I used to debug the non-existing output buffer and/or output window is attached as [live-py-mode.el.txt](https://github.com/donkirkby/live-py-plugin/files/753127/live-py-mode.el.txt) for the records.

**Comment by donkirkby** [comment]
Thanks for the improvements and the documentation, @brandm. I'll try it out.

**Comment by donkirkby** [comment]
Improvements merged, closing the issue.

Thanks, @brandm.
