### ISSUE TITLE
Change key map for Emacs mode

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#101]
From a comment by @brandm in issue #99, the keys I'm using now are supposed to be left for the [user] to define.

>The EmacsManual says that the combination of C-c followed by a plain letter, and the function keys f5 through f9 are reserved for users.

Suggested new mappings:
* `C-c M-d` set driver script or module
* `C-c M-w` set working directory
* `C-c M-p` set Python path
* `C-c M-v` set Python version
* ~~`C-c M-l` toggle Live Python mode~~

[user]: https://www.emacswiki.org/emacs/ChoosingKeysToBind

**Comment by brandm** [comment]
Thank you for the prompt fix.
