### ISSUE TITLE
Python file with space breaks live preview in Emacs

### ISSUE THREAD

**Issue by teodorlu** [donkirkby/live-py-plugin#104]
Hello!

Thanks again for the great plugin :)

## Preface

This behavior seems to affect
1. File names with space in them
2. Folder names with space in them.

I don't need to create python files with space in them, so I'm reporting 2.

## System

- GNU Emacs 25.1.1 (x86_64-mingw32) of 2016-11-15
- Spacemacs 0.200.7@25.1.1

Tested with two versions of live-py:
- live-py-mode-20170125.2135
- live-py-mode-20170204.1555

## Steps to reproduce

1. Create the file `D:\some folder\script.py`
2. Start live-py-mode

## Observed behavior

Error message:
```
Traceback (most recent call last):
  File "c:/Users/thlhe/.emacs.d/elpa/live-py-mode-20170204.1555/code_tracer.py", line 967, in <module>
    main()
  File "c:/Users/thlhe/.emacs.d/elpa/live-py-mode-20170204.1555/code_tracer.py", line 947, in main
    with open(args.source, 'rU') as source:
IOError: [Errno 2] No such file or directory: 'folder/script.py'
```

## Expected behavior

Live-py starts normally. Normal behavior is observed if I rename the file to `D:\some_folder\script.py`.

**Comment by donkirkby** [comment]
Thanks for the bug report, it's a standard problem with using string concatenation to build a shell command. Looks like I need to use a [quote] function to avoid the problem.

Glad you like the plugin. Do you mind if I ask how you use it? Are you just experimenting with it, or do you use it regularly? How long have you been writing Python code?

[quote]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Shell-Arguments.html

**Comment by teodorlu** [comment]
If I'm writing a script, I just fire up live-py to see what I'm doing. Live
coding is a tad faster than rerunning the script manually. In addition, there's
no need for `print`s all over the code that have to be removed later.

If it's a library, I'm typically working on a function. I'll outline the
function and its parameters, and write a function that tests it below.

From my memory of yesterday:

```python
def find_spring_node_candidates(node_index, elements, springs):
    """
    Find reasonable candidates for which node to put the springs.
    
    node_index: dict from node id to x, y and z
    elements: table of elements with element number, node 1 and node 2
    springs: table of x-coordinate and spring stiffnesses kz, kxx and kyy
    """
    # Develop here
    
def test_springs():
    loader = Loader()
    elements = loader.fetch_elements()
    nodes = loader.fetch_nodes()
    node_index = index_on_first(nodes)
    springs = loader.fetch_springs()
    find_spring_node_candidates(node_index, elements, springs)

test_springs() # I comment this in developing the function and out otherwise.
```

That lets me see what I'm doing while coding. Having the actual value of the
variable _right there_, not just some name I'm assuming is this.

Live-py my goto when I'm starting with Python. If I'm inflicting some kind of
effect on the OS (moving files, renaming), I tend to avoid it to prevent calling
unfinished commands. Otherwise, I use it untill I hit the "execution limit
reached" (any plans for being able to execute live-py on a keystroke instead of
auto? Would still be useful to see variables right next to where they are
defined, without having to do the print thing). When that limit is reached, I'm
working against a repl loading code into it and putting some `print`s around to
see what's happening. I have been using live-py for about two months.
Incidentally, I stumbled upon it not long after having found Bret Victor's
videos.

I touched on Python second year at university. I started doing serious Python
1.5 years ago, when I started working. Work is related to structural analysis,
"does this construction hold, what are the forces and deflections".

**Comment by donkirkby** [comment]
I quoted the shell arguments, let me know if I missed any.

Instead of commenting and uncommenting your test code, you can do this:

    if __name__ == '__live_coding__':
        test_springs()

If you are writing unit tests, you can use those to drive your live coding by setting the live coding driver script to something like this:

    -m unittest test_module.TestClass.test_method

Type `C-h m` and look for the **Live-Py** section to see all the shortcut keys for setting the driver and other things.

As for running code on a keystroke, I would just map `live-py-mode` to a user key like `C-c l`. Then toggle live mode on when you want to see the results and toggle it off when you want to do some editing. When I'm worried about the file system, I pass an open file into the function, and then make the unit test pass in a `StringIO` object. That way my live coding session and unit test are all in memory with no files to clean up.

**Comment by donkirkby** [comment]
Oh, and thanks for telling me how you use the plugin. It helps me think about new features.

**Comment by donkirkby** [comment]
We should not quote the driver argument, because it breaks for drivers with their own arguments. For example:

    -m unittest test_module.TestClass.test_method

**Comment by teodorlu** [comment]
Another usage comment: Live-py really shines when I'm exploring functions/packages I haven't used before. What does this function do? See it at once. Is the argument of this type? No, the error says it should be this. Easy to fix.

The experience is really pleasant, somewhat similar to using [Figwheel](https://www.youtube.com/watch?v=j-kj2qwJa_E) for web sites. [Spyder](https://pythonhosted.org/spyder/) is a neat complement for numerics (Numpy, pandas). Whereas Live-py is perfect for the "time"-dimensjon, Spyder hits the mark on the "variable direction"; it cannot show values over time and during the code, but at a specific time, it's possible to explore all currently available variables, including nesting. See the variable explorer to the right, found [here](http://www.marsja.se/rstudio-like-python-ides-rodeo-spyder/):

![](http://www.marsja.se/wp-content/uploads/2016/01/Spyder.png)

I don't really see how it's possible to combine. Live-py already uses screen estate efficiently.

**Comment by donkirkby** [comment]
Thanks for the link, @teodorlu, I hadn't seen Spyder before. Some day, I might build a graphical display that lets you expand variables like a debugger does, but I like the simple text display for now.

**Comment by teodorlu** [comment]
Yeah, I'm just throwing ideas out there in case anything might be useful. You know best where your effort is best put to use.
