### ISSUE TITLE
Using live-py with Abaqus' python distribution

### ISSUE THREAD

**Issue by teodorlu** [donkirkby/live-py-plugin#121]
Hello again,

Disclamer: I wrote this before having read the built in Emacs documentation.

## System information

* Windows 10
* System Python: `Python 2.7.13 :: Anaconda 4.3.1 (64-bit)`
* GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-11-15
* Spacemacs v.0.200.9
* live-py-mode-20170429.2207
* Abaqus 2017
* `abaqus python --version` gives 2.7.3

## Overview

I'd like to use Live-py with [Abaqus](https://en.wikipedia.org/wiki/Abaqus)' python distribution. The [documentation](http://ivt-abaqusdoc.ivt.ntnu.no:2080/v2016/books/cmd/default.htm) is usually comprehensive.

I've tried various things, probably in all the ways they were not intended. Not sure if this can be done in Live-py, but I'd really like to give it a shot.

I'll try to provide any other debug information that may be useful.

## Step 1: live-py-set-version with python interpreter and arguments

Using `M-x live-py-set-version`, I was able to specify a custom python interpreter.

To run Python applications in an Abaqus context, the command `abaqus python` can be used; thus if I want to run my `own_script.py`, I execute `abaqus python own_script.py` in a terminal. I then have access to the custom Abaqus imports that allows me to interact with FEM models and analysis results. The `abaqus` command resolves to the batch script `C:\SIMULIA\Commands\abaqus.bat` on my system, which starts `C:\SIMULIA\CAE\2017\win_b64\code\bin\ABQLauncher.exe` with any arguments list (eg `python own_script.py` passed through). The executable then again passes control to a bundled python.exe, after doing some magic that allows me to access the API. I haven't been able to load the API on a python.exe of my choosing without going through this magic executable.

When I `M-x live-py-set-version` `"c:/SIMULIA/Commands/abaqus.bat python"`, I get this in the preview Window:

```
'"c:/SIMULIA/Commands/abaqus.bat python"' is not recognized as an internal or external command,
operable program or batch file.
```

* _Is it possible to specify arguments to the Python interpreter used with `live-py`?_

## Step 2: Custom batch script that wraps arguments

1. I create `apyth.bat` in the same directory as `own_script.py` containing
    ```
    "C:\SIMULIA\Commands\abaqus.bat" python %*
    ```
2. I set my `M-x live-py-set-version` to `apyth`, and it seems to be getting a little further:
    ```
    d:\workspace\python>"C:\SIMULIA\Commands\abaqus.bat" python "c:/Users/thlhe/.emacs.d/elpa/live-py-mode-20170429.2207/code_tracer.py" -f "d:/workspace/python/abaqus_live.py" - abaqus_live python 
    Traceback (most recent call last):
      File "c:/Users/thlhe/.emacs.d/elpa/live-py-mode-20170429.2207/code_tracer.py", line 23, in <module>
        arg = locate('ast.arg')
      File "C:\SIMULIA\CAE\2017\win_b64\tools\SMApy\python2.7\lib\pydoc.py", line 1471, in locate
        nextmodule = safeimport(join(parts[:n+1], '.'), forceload)
      File "C:\SIMULIA\CAE\2017\win_b64\tools\SMApy\python2.7\lib\pydoc.py", line 310, in safeimport
        raise ErrorDuringImport(path, sys.exc_info())
    pydoc.ErrorDuringImport: problem in ast.arg - <type 'exceptions.ImportError'>: No module named arg
    ````
3. Seems like the `locate` function behaves differently with the two python interpreters, returning `None` on Anaconda Python 2.7 and throwing an error with Abaqus Python 2.7:
    ![image](https://cloud.githubusercontent.com/assets/5285452/26246757/0d1eee16-3c9b-11e7-8b0b-73fb62875d65.png)

## Step 3: Attempting to fix the `locate` issue

I tried modifying the beginning of `code_tracer.py` to this to wrap the error:

```python
import pydoc # no longer import the locate function
import sys
import traceback
import types
import os
import importlib

from canvas import Canvas
from mock_turtle import MockTurtle
from report_builder import ReportBuilder

# Instead, wrap it in a try-catch
def locate(*args, **kwargs):
    try:
        return pydoc.locate(*args, **kwargs)
    except ImportError:
        return None
```

But I still kept getting the same error. My suspect is my lack of understanding plugin internals.

## Summary

1. Trying to specify which abaqus interpreter to use was a little clunky, especially with command line arguments. `live-py-set-version` may be the wrong function to use? Is there a better way?
2. I'd like feedback on how to fix the error with `locate`.

Ideas?

**Comment by donkirkby** [comment]
Thanks for describing the problem, @teodorlu. Using the custom batch script is the best option right now. I'll try to think of another option that will still support paths with spaces in the name, as described in issue #104.

As for the problem with `pydoc.locate()`, that sounds like a bug in Abaqus. Unfortunately, `pydoc.locate()` is undocumented, so I don't know if the authors of Abaqus will care. Do you know if there's a way to submit bug reports to Abaqus? If you're interested, try running this in Abaqus to see exactly where the problem is:

```
# Try this with Abaqus Python 3.
from pydoc import locate

try:
    import bogus
except ImportError as ex:
    print(repr(ex))
    print(ex.name)

try:
    import sys.bogus
except ImportError as ex:
    print(repr(ex))
    print(ex.name)
```

Here's how it looks in Live Py:

    # Try this with Abaqus Python 3. | 
    from pydoc import locate  | 
                              | 
    try:                      | 
        import bogus          | 
    except ImportError as ex: | ex = ImportError("No module named 'bogus'",) 
        print(repr(ex))       | print('ImportError("No module named \'bogus\'",)') 
        print(ex.name)        | print('bogus') 
                              | 
    try:                      | 
        import sys.bogus      | 
    except ImportError as ex: | ex = ImportError("No module named 'sys.bogus'; 'sys' is not a package",) 
        print(repr(ex))       | print('ImportError("No module named \'sys.bogus\'; \'sys\' is not a package",)') 
        print(ex.name)        | print('sys.bogus') 


You're workaround looks like it's close. Try catching `ErrorDuringImport` instead of `ImportError`.

**Comment by teodorlu** [comment]
Yeah, I wouldn't be surprised if this is an Abaqus bug. They tend to try to control everything, and reimplement anything they can. They even built their own Python development environment that they want people to use. It's not good.

Abaqus supports python 2 only. Running your script outside of live-py (`abaqus python issue_121.py` gives this output:
```
ImportError('No module named bogus',)
Traceback (most recent call last):
  File ".\issue_121.py", line 8, in <module>
    print(ex.name)
AttributeError: 'exceptions.ImportError' object has no attribute 'name'
```

**Comment by donkirkby** [comment]
I just removed the dependency on `pydoc.locate()` by going back to catching import errors. The code's a little uglier, but it's more reliable.

**Comment by donkirkby** [comment]
I added the `live-py-set-args` command (`C-c M-a`). You should be able to set the version to `abaqus` and the args to `python`.

**Comment by teodorlu** [comment]
I haven't had the time to test with Abaqus, but this looks really promising! I'll report back when I've tried.

**Comment by teodorlu** [comment]
Confirmed, working! Thanks a lot!

Note: Live-py seems to look for an `abaqus` executable in the current directory on Windows. I'd expect it looking through the system path. This doesn't bother me, though. Increased productivity using live-py greatly outweighs having to write `C:\SIMULIA\Commands\abaqus.bat` instead of `abaqus` or `abaqus.bat`.

![image](https://user-images.githubusercontent.com/5285452/26920425-504d045e-4c39-11e7-800a-fecd1821582f.png)
![image](https://user-images.githubusercontent.com/5285452/26920487-733e452c-4c39-11e7-89ba-8511e703de4d.png)

If I create a local batch script, it works:

![image](https://user-images.githubusercontent.com/5285452/26920574-b4d3c250-4c39-11e7-830b-3a7a9431866e.png)

Specifying the full path also works:

![image](https://user-images.githubusercontent.com/5285452/26920659-f0f2ba48-4c39-11e7-8031-21d99f264bc8.png)

**Comment by donkirkby** [comment]
I noticed the same thing on Ubuntu when specifying a virtualenv or Python 3, so I've opened issue #123.

Thanks for letting me know that the interpreter arguments are working.
