### ISSUE TITLE
Live-py crashes when modifying the `locals()` dict

### ISSUE THREAD

**Issue by teodorlu** [donkirkby/live-py-plugin#122]
Hello,

This works on my `Python 2.7.13 :: Anaconda 4.3.1 (64-bit)` system, but not when run through Live-py with the same Python as backend:

```python
rF = -3
tF = 9
dF = -2

myenv = locals()

for k in myenv:
    if len(k) == 2 and k[1] == "F":
        myenv[k] = max(1, myenv[k])

print rF, tF, dF
# should print "1 9 1"
```

I get this message:

```
rF = -3 
tF = 9 
dF = -2 

myenv = # ... removed huge dict

k = '__live_coding_context__' RuntimeError: dictionary changed size during iteration 
```

I guess you're using the `locals()` dictionary for tracing variables?

I don't _need_ this, so your choice if this is a bug or limits to use :)

**Comment by donkirkby** [comment]
You're right, I'm storing some state in local variables with strange names to avoid collisions, but I didn't think of this problem.

I recently learned a trick for storing state in stack frames, so I might be able to avoid polluting the local variables.

**Comment by donkirkby** [comment]
I'm having trouble reproducing the problem. I copied your example script to `~/scratch.py`, and ran it like this:

```
$ cd ~/.emacs.d/elpa/live-py-mode-20170524.2216/
$ python -V
Python 2.7.12
$ python ~/scratch.py 
Traceback (most recent call last):
  File "/home/don/scratch.py", line 7, in <module>
    for k in myenv:
RuntimeError: dictionary changed size during iteration
$ python code_tracer.py --dump ~/scratch.py
    rF = -3                             | rF = -3 
    tF = 9                              | tF = 9 
    dF = -2                             | dF = -2 
                                        | 
    myenv = locals()                    | myenv = {...giant dict...} 
                                        | 
    for k in myenv:                     | k = '__live_coding_context__' RuntimeError: dictionary changed size during iteration 
        if len(k) == 2 and k[1] == "F": | 
            myenv[k] = max(1, myenv[k]) | 
                                        | 
    print rF, tF, dF                    | 
    # should print "1 9 1"              | 
```

So I see the same behaviour whether I'm using Live Python or not. Can you please run the same test with your version of Python?

If you just want to fix this specific problem, define `k` before entering the loop. That way you don't define any new local variables inside the loop.

    rF = -3                             | rF = -3 
    tF = 9                              | tF = 9 
    dF = -2                             | dF = -2 
                                        | 
    myenv = locals()                    | myenv = {...giant dict...} 
                                        | 
    k = None                            | k = None 
    for k in myenv:                     | k = '__live_coding_context__' | k = '__builtins__' | k = 'myenv' | k = '__package__' | k = 'dF'        | k = 'rF'        | k = 'tF'        | k = '__name__' | k = '__doc__' | k = 'k' 
        if len(k) == 2 and k[1] == "F": |                               |                    |             |                   |                 |                 |                 |                |               | 
            myenv[k] = max(1, myenv[k]) |                               |                    |             |                   | myenv['dF'] = 1 | myenv['rF'] = 1 | myenv['tF'] = 9 |                |               | 
                                        | 
    print rF, tF, dF                    | print 1, 9, 1 
    # should print "1 9 1"              |

**Comment by teodorlu** [comment]
This is _not_ an issue with Live-py. Sorry for the noise!

The reason it even worked in the first place, was because k was already defined.

I originally ran the program through the an IPython repl inside Emacs:

1. Open `scratch.py` in Emacs with Spacemacs' `python` layer
2. `M-x python-start-or-switch-repl`
3. `M-x python-shell-send-buffer`. This causes the same error as you describe on
    the _first_ run!
4. `M-x python-shell-send-buffer` again. Now works.

... which would cause `k` already to be defined on the second run. When I define
`k` outside the loop, the code works in Live-py, in normal python and in the
IPython repl, _without_ running twice.

Closing this, then!

**Comment by donkirkby** [comment]
No worries. Let me know if you see anything else weird.
