### ISSUE TITLE
Unpacking from a generator doesn't show

### ISSUE THREAD

**Issue by sr105** [donkirkby/live-py-plugin#128]
live-py-mode Version: 2015
Emacs 25.1 (OSX)
Python 3.5.2

The result of the 2nd line doesn't show:

    x, y = 1, 2                      | (x, y) = (1, 2)
    x, y = (n for n in (1, 2))       | <nothing>
    x, y = [n for n in (1, 2)]       | (x, y) = [1, 2]

**Comment by donkirkby** [comment]
Good suggestion, I'll take care of it.

**Comment by donkirkby** [comment]
Reopening for a related issue: multiple assignments still have this problem. Here's an example:

    x, y = 1, 2                    | (x, y) = (1, 2) 
    x, y = (n for n in (1, 2))     | (x, y) = (1, 2) 
    x, y = [n for n in (1, 2)]     | (x, y) = (1, 2) 
    x, y = z = (n for n in (1, 2)) | 
    x, y = z = 1, 2                | (x, y) = z = (1, 2) 

Make the last two lines give the same display.

**Comment by donkirkby** [comment]
I just remembered why I didn't handle this scenario. `z` ends up as an empty iterator.

    x, y = 1, 2                    | (x, y) = (1, 2) 
    x, y = (n for n in (1, 2))     | (x, y) = (1, 2) 
    x, y = [n for n in (1, 2)]     | (x, y) = (1, 2) 
    x, y = z = (n for n in (1, 2)) | 
    print(x, y, list(z))           | print (1, 2, []) 
    x, y = z = 1, 2                | (x, y) = z = (1, 2) 
    print(x, y, list(z))           | print (1, 2, [1, 2])
