### ISSUE TITLE
ImportError: No module named pandas 

### ISSUE THREAD

**Issue by dewade2003** [donkirkby/live-py-plugin#130]
import pandas as pd
import numpy as np

**Comment by dewade2003** [comment]
import pandas as pd
import numpy as np

**Comment by donkirkby** [comment]
Are you using Emacs, Eclipse, or PyCharm? How many versions of Python do you have installed, and which ones have pandas and numpy?

If you're using Emacs, you can probably solve the problem with `C-c M-v` to select the version of Python with pandas and numpy. You have to give it the full path to the Python command. You can also activate a virtualenv before you launch Emacs.

**Comment by donkirkby** [comment]
Since I haven't heard anything in a month, I assume that you got it working.

Closing the issue.
