### ISSUE TITLE
Find a license that's compatible with Emacs

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#131]
I was contacted by someone from the [emacs-dev] mailing list about the license I'm using. It's not compatible with the GPL that Emacs uses, so they asked if I would change my license. I think I chose the EPL just because I was publishing an Eclipse plugin, so I just need to make sure that I can find a license compatible with all three platforms. Perhaps the [MIT] license?

* [x] Emacs - MIT is compatible
* [x] Eclipse - other plugins use MIT, seems compatible
* [x] PyCharm

[emacs-dev]: https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html
[MIT]: https://choosealicense.com/licenses/mit/

**Comment by donkirkby** [comment]
@brandm, I was switching all the license declarations for this issue, when I noticed you have a copyright declaration in your name on the [Emacs tests][1] you added back in April. Two questions:

1. Do you mind if I switch the license on that file from EPL to MIT?
2. Are you willing to transfer copyright of that file to me? I'm happy to leave you as the author.

[1]: https://github.com/donkirkby/live-py-plugin/blob/master/emacs-live-py-mode/live-py-test.el#L3

**Comment by brandm** [comment]
> @brandm, I was switching all the license declarations for this issue, when I noticed you have a copyright declaration in your name on the Emacs tests you added back in April. Two questions:
>
> 1. Do you mind if I switch the license on that file from EPL to MIT?

I don't mind.

> 2. Are you willing to transfer copyright of that file to me? I'm happy to leave you as the author.

I'm OK with that too.

**Comment by donkirkby** [comment]
Thanks for that, and thanks for all your contributions.
