### ISSUE TITLE
Spacing around print output

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#165]
At least add a space after print output, and possibly a pipe.
Here's an example:

    import sys                                                     | 
                                                                   | 
    x = sys.stdout.write(''.join(map(lambda c: c.upper(), 'abc'))) | ('a' => 'A') | ('b' => 'B') | ('c' => 'C') sys.stdout.write('ABC')x = None 

At least add a space before the `x = None`. Maybe add pipes, as between the lambda calls.

**Comment by lizardstarks** [comment]
Looks like the space is already present before the x when I test this now, so the output looks like:
`
('a' => 'A') | ('b' => 'B') | ('c' => 'C') sys.stderr.write('ABC') x = None 
`

But maybe that could be formatted like:
`
('a' => 'A') | ('b' => 'B') | ('c' => 'C') | sys.stderr.write('ABC') | x = None 
`

**Comment by donkirkby** [comment]
Closed by pull request #186.
