### ISSUE TITLE
Enable Intellij integration

### ISSUE THREAD

**Issue by jeshan** [donkirkby/live-py-plugin#189]
Hey Don,
Would really like to try this but I use only Intellij Ultimate with Pycharm on it. Could you enable integration with Intellij as well?

**Comment by donkirkby** [comment]
That's strange, I don't know why it doesn't show up when you search the plugin repository from IDEA.

I'll try to fix that, but as a workaround, you can [download] the plugin's jar file, and click the "Install from disk..." button.

[download]: https://plugins.jetbrains.com/plugin/9742-live-coding-in-python

**Comment by donkirkby** [comment]
I posted a question on the IntelliJ [support forum].

Did my suggested workaround work for you?

[support forum]: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000058630-Allow-my-plugin-to-install-on-IDEA

**Comment by jeshan** [comment]
I tried the workaround even before you suggested it. It installed but
didn't work outside the box. I'll get back to you asap on this.

Also, I checked your question on support forum.
From what I can guess, the issue is because you're depending on
com.intellij.modules.python which is available only in PyCharm.
I think you should depend only on the modules available in most IDEs.

I'm comparing your plugin.xml with the ignore plugin which is compatible to
most IDEs:

https://github.com/hsz/idea-gitignore/blob/master/resources/META-INF/plugin.xml#L102-L103

There they are not depending only on **.lang and on the Git4Idea plugin.
Maybe you should apply the same idea here, i.e depend only on platform or
lang module and also list Python plugin as a dependency.

(Note that I'm a total noob in plugin dev; I'm just inferring from what I
read)

**Comment by jeshan** [comment]
Looking further into it now, I saw 2 PyCharm plugins that you can compare.

First one is listed as compatible with PyCharm only:
https://github.com/andreisilviudragnea/PythonDCE/blob/master/resources/META-INF/plugin.xml#L21

Second one works cross-IDE:
https://github.com/aristotll/python-typing-adder/blob/master/resources/META-INF/plugin.xml#L40-L43

Compare how they listed their dependencies and you will find your answer.

**Comment by donkirkby** [comment]
Thanks, I'll check those out. If you still have problems after installing the plugin from disk, please create another issue with all the details you can give me. 
Thanks for the bug report.
