### ISSUE TITLE
Matplotlib not showing plot image

### ISSUE THREAD

**Issue by salvor7** [donkirkby/live-py-plugin#190]
I tried turning on live coding for this code
    import matplotlib.pyplot as plt
    plt.plot([3,14])
    plt.show()
and got the following output, which I think is an error.
    start_canvas
    create_image
        283
        58
        image='iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAYAAAA1...
    end_canvas

Is this expected atm?

**Comment by donkirkby** [comment]
It looks like the fix for handling different line endings doesn't always work. I can reproduce the problem, and it's receiving`\n` linefeeds on Windows. I'll try using a buffered reader to handle the line breaks so I don't have to.
