### ISSUE TITLE
currently active virtualenv is not respected

### ISSUE THREAD

**Issue by skebanga** [donkirkby/live-py-plugin#201]
# What I did

In emacs (specifically spacemacs), having activated my pipenv virtualenv (`pipenv-activate`), entering `live-py-mode` fails to use the active virtualenv.

Eg: Attempting to import a module which is installed in the virtualenv fails.

Note that if I execute a local file (`python-execute-file-focus`) the code runs inside my virtualenv, and works as expected 

Describe the steps you took, probably including your Python code, like this:

- Start Emacs
- Activate pipenv virtualenv (`pipenv-activate`).
- Enter live-py mode (`live-py-mode`)
- import module which is installed in virtualenv
- import fails

# What happened
```
ImportError: No module named pandas
```

# What I wanted to happen
My currently active virtualenv takes precedence

# My environment

- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b68bd33a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp
      (smart-tabs :variables smart-tabs-default-insinuations
                  '(c c++))
      protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by donkirkby** [comment]
Thanks for the detailed report,  I hadn't heard of the pipenv integration.
For now,  you can work around the problem by selecting the python binary in your virtualenv with `C-c M-v`. Another option is to activate the virtualenv before launching Emacs.
I will also take a look at detecting the pipenv integration if it's installed.

**Comment by donkirkby** [comment]
Thanks for reporting this issue, but I don't see a good way to fix it. I looked at Emacs integration with virtualenv, and I see several options. It's not clear to me which one I should support, so I'm going to close this issue and wait to see if the community picks a standard.

For now, you can use either of the workarounds above, or write your own Emacs code that sets the `live-py-version` variable.
