### ISSUE TITLE
Blank display in Eclipse

### ISSUE THREAD

**Issue by joyshah** [donkirkby/live-py-plugin#202]
1.I have freshly installed pydev.
2. Restarted eclipse.
3. Installed live coding plugin.
4. Restarted eclipse.
5. Written some code(for loop)
6. Runs fine on console.
7. Started live coding.
8. Started showing live coding window on right side.
9. Doesn't show anything in that window.
10. Tried on different interpreter like 2.7,3.6,3.0-3.5

Eclipse Version:
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200

**Comment by donkirkby** [comment]
Thanks for the report. What operating system are you using?

**Comment by joyshah** [comment]
Windows 10

**Comment by donkirkby** [comment]
Interesting. It might be as simple as a problem with line endings, then. I had similar problems in #190 with PyCharm on Windows. I'll try to install Eclipse on Windows and reproduce the problem.

**Comment by vidhyaa11** [comment]
i too face the same problem. and my os is windows 7

**Comment by donkirkby** [comment]
It looks like `org.python.pydev.runners.UniversalRunner` has moved to `org.python.pydev.ast.runners.UniversalRunner`. Should be simple to fix by changing the import.

**Comment by donkirkby** [comment]
If you need to workaround this until I publish the fixed release, you can roll back to an older version of PyDev. It worked for me with version 6.0.0.
