### ISSUE TITLE
Special Characters Support - PyCharm

### ISSUE THREAD

**Issue by wjuniorhp** [donkirkby/live-py-plugin#224]
# What I did
This error can be reproduced with a single line of code:

```
a = 'Paçoca'
```

# What happened
The live code panel simply outputs this:

```
null
```

# What I wanted to happen
I want the live code panel to show the actual value of the variable, even with special characters like ç, ã, é, etc.
A single line of code containing a single one of these characters is enough to output a single "null" on the live code panel.
What I want to see on the panel, with the code presented above, is:
```
a = 'Paçoca'  
```

# My environment
* Editor: PyCharm 2019.1.1 (Community Edition)
              Build #PC-191.6605.12, built on April 3, 2019
              JRE: 11.0.2+9-b159.34 amd64
              JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Operating system: Windows 10 Pro 1809
* Python:
              Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Comment by donkirkby** [comment]
Thanks for the report, @wjuniorhp. I tried it on Ubuntu 18.04 with the same PyCharm version that you report, and it works fine.

It might be a Windows problem, so I'll try it there next.

Can you please check your encoding settings? Look under Editor: File Encodings. Mine defaulted to UTF-8.

Also, please try running this script, then turning on live coding.

    a = 'Paçoca'
    print(a)

**Comment by wjuniorhp** [comment]
This is what I see under Editor > File Encodings. Apparently, mine is UTF-8 too.
![image](https://user-images.githubusercontent.com/23110409/57414792-0276ff00-71d0-11e9-9b8b-4b4fb0d8e7ed.png)
By running what you asked, I still get "null" on the live code panel, and it prints "Paçoca" on the console, as expected.
Thank you for your help.

**Comment by donkirkby** [comment]
It looks like Java doesn't use UTF8 by default on Windows, so I specified it explicitly. I'll put out a patch release in the next few days.

**Comment by wjuniorhp** [comment]
Thank you very much
