### ISSUE TITLE
Notify user when live coding can't start

### ISSUE THREAD

**Issue by erfantkerfan** [donkirkby/live-py-plugin#230]
# What I did
I installed pychram licenced it and wrote this code then clicked on start live coding bith via shortcut and run menu

```
print('hello world')

i = 1

```

# What happened
the plugin simply didn't worked at all

# My environment
Describe the versions of everything you were using:
* Editor PyCharm 2018.3.5 pro
* Operating system win 10 1803
* Python 3.7

# Update
This issue is now to add notifications when the live coding mode can't start in PyCharm.

**Comment by donkirkby** [comment]
I noticed that the PyCharm instructions weren't very clear, so maybe you were just missing one of the steps. Please try these improved instructions, and let me know if that solves the problem for you.

1. From the File menu, choose Settings....
2. Click on the Plugins section.
3. Click the Browse Repositories... button.
4. Type live coding in the search box, and click on the "Live Coding in Python"
    entry in the list below.
5. Click the green Install button on the right.
6. Click the Restart PyCharm button.
7. Close all the dialog boxes by clicking OK, then let PyCharm restart when it
    asks.
8. Open a Python file.
9. Run the Python file normally, as a script or a unit test.
10. With the same run configuration selected in the drop down, choose Start
    Live Coding from the Run menu.

**Comment by erfantkerfan** [comment]
sorry
i didn't assign the extension to the file and pycharm run it anyway so I didn't suspect that.
added .py extemsion and wola
thanks
issue closed

**Comment by donkirkby** [comment]
It would be much clearer if the plugin [notified] the user why it couldn't start. In this case, the open file is not a Python file. I think there are a few other reasons that it fails to start, so try to add notifications for all of them.

[notified]: https://www.jetbrains.org/intellij/sdk/docs/user_interface_components/notifications.html

**Comment by donkirkby** [comment]
I think this is less confusing since #245 deactivated the start and stop buttons on files that aren't Python, so I'm closing this issue.
