### ISSUE TITLE
Live Coding Output Scrolling Issue

### ISSUE THREAD

**Issue by IfMeElse** [donkirkby/live-py-plugin#277]
# What I did
I typed the following
```
print("ciao")
k = 32
for i in range(10):
    k +=1
```

# What happened
The output was just perfect.
```
print('ciao')
k = 32
i = 0  | i = 1  | i = 2  | i = 3  | i = 4  | i = 5  | i = 6  | i = 7  | i = 8  | i = 9
k = 33 | k = 34 | k = 35 | k = 36 | k = 37 | k = 38 | k = 39 | k = 40 | k = 41 | k = 42 
```
As I'm using a narrow tab, not all the output is visible and I need to scroll right in order to see the part that is not visible.
**Here is the issue:** I can't scroll right as the window is constantly scrolling back left.

# What I wanted to happen
I would have wanted the tab to scroll effortlessly or the text to be wrapped to tab  width

# My environment
* Editor: Sublime text Version3.2.2
* Operating system: macOS Mojave 10.14.6 
* Python: 3.8

**Comment by donkirkby** [comment]
Thanks for the bug report, I hadn't noticed the problem. I'll figure out how to read the horizontal position and restore it after updating the display.
