### ISSUE TITLE
Subscript assignment in Python 3.9

### ISSUE THREAD

**Issue by vijayk22** [donkirkby/live-py-plugin#289]
# What I did
I want to see live coding variable values for a numpy array created as below and assigning a value to one of the element.

```
import numpy as np

tempArr = np.zeros(5)
tempArr[0] = 0 #problematic line
print(tempArr)

```

# What happened
Everything works but as soon as assignment expression  is executed no output is shown in live code. (PyCharm plugin)

```
tempArr[0] = 0
```

# What I wanted to happen
I would like to print all lines in live code including assignment line as blank line.

```
tempArr = array([0., 0., 0., 0., 0.])

print('[0. 0. 0. 0. 0.]')
```

# My environment
Describe the versions of everything you were using:
* Editor PyCharm
* Operating system MacOS
* Python 3.9

# Other feedback
I a new python learner and enjoyed Live Code thoroughly. Planning to use it as much as possible but above error is stopping me to use it.
Thanks for making such a great tool !

**Comment by vijayk22** [comment]
![image](https://user-images.githubusercontent.com/17021234/103189792-3ca08300-4883-11eb-9183-63b998e75619.png)

**Comment by donkirkby** [comment]
Thanks for the bug report. It looks like a problem with Python 3.9, so I'll dig into it.
It doesn't seem related to numpy, because this fails in the same way:

```
tempArr = [0] * 5
tempArr[0] = 0  # problematic line
print(tempArr)
```

There's probably some new class in the `ast` module that I have to support.

**Comment by vijayk22** [comment]
Hi @donkirkby - thanks for prompt fix.
Quick question: how can I get this latest update in PyCharm plugin ? Thanks!

**Comment by donkirkby** [comment]
You're welcome. I'll put out a new release after fixing another bug or two, hopefully in the next couple of weeks. If you don't want to wait, you could follow the instructions for building your own release in the `CONTRIBUTING.md` file.

**Comment by vijayk22** [comment]
Okay thanks! appreciate your prompt response and fix.

**Comment by donkirkby** [comment]
The new release is available today. You should be able to update the plugin in PyCharm's settings.

**Comment by vijayk22** [comment]
Thanks a lot !
