### ISSUE TITLE
Does not work with Python Community Edition plugin in other Jetbrains IDEs

### ISSUE THREAD

**Issue by liurui39660** [donkirkby/live-py-plugin#293]
## What I did

1. Open CLion
2. Create `main.py`
3. Write some code, e.g. `a = 1`
4. Run it normally
5. Run it again by clicking "Start Live Coding"
6. Try to add more code, e.g., `b = 2`

## What happened

In the split window, line 1 shows `created for main.py`. After updating the code, nothing changes.

## What I wanted to happen

Show variable names their values like how this plugin works in PyCharm.

## My environment

* CLion 2020.3.3
* Windows 10 Pro
* Python 3.7.9

## Other feedbacks

Change github issue template to use `##` for section names, `#` is usually used as titles.

**Comment by donkirkby** [comment]
Thanks for the bug report. Can you please include the version of the Python plugin that you installed in CLion, as well as the version of the live coding plugin? When you say you run it normally, do you mean that you create a Python run configuration in CLion and start it?

**Comment by liurui39660** [comment]
Sure, they are the latest version in the marketplace, Python Community Edition 203.7717.62, and Live Coding in Python 2.25.1.

Yes, just the regular way to run a python script file, that step is to ensure the configuration is created and selected.

I think a screenshot can help explain the actual behavior.

![image](https://user-images.githubusercontent.com/20491264/113170044-c4c66800-9278-11eb-8abe-b14e1168cb69.png)

**Comment by donkirkby** [comment]
OK, that's a good clue to the problem. The [latest version] of my plugin isn't 2.25.1, it's 4.3.0. However, it doesn't support CLion for some reason. I suspect that if you download the jar file and install that into CLion it will work. I'll see if I can figure out why the dependencies are wrong before I put out the next release.

[latest version]: https://plugins.jetbrains.com/plugin/9742-live-coding-in-python/versions

**Comment by liurui39660** [comment]
Thanks. I manually installed the 4.3.0 to CLion (and uninstalled 2.25.1), but it is still the same result. 

Whenever I update the script while the live coding is running, the same line of log is appended to `idea.log`.

```
2021-04-01 12:00:18,164 [ 334872]   INFO - m.pty4j.windows.WindowsVersion - Windows version: 10.0.19041 
```

The timestamp may be different, but log body is the same.

**Comment by donkirkby** [comment]
OK, I guess I'll install CLion on Windows to see if I can reproduce the problem. Something seems odd, though, because CLion should show the latest version of my Plugin in the marketplace, as long as you've got the Python plugin installed.

I changed the dependency in issue #228 to follow the guidance in [this post], where it says:

>The fix has been deployed and now your plugin with `<depends>com.intellij.modules.python</depends>` would be available in IntelliJ IDEA, Android Studio, CLion, DataGrip, GoLand, PyCharm, Rider. When installing plugin in IDEs other than PyCharm it would be suggested to install Python (for IDEA Ultimate) or Python Community Edition plugin.

Now that I read that more carefully, I think it should show my plugin even before you install the Python plugin. It will just suggest that you install Python as well. Weird.

[this post]: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000058630

**Comment by liurui39660** [comment]
Things start to become interesting. 

I can install Python, but it requires another plugin `com.intellij.modules.python-pro-capable` which is not available in the marketplace. And Live Coding in Python (4.3.0) shows it requires `com.intellij.modules.python`. But if I remove Python, Live Coding in Python no longer complains.

Another side, without Python, if I disable the bundled Python Community Edition, it shows `io.github.donkirkby.livepycharm` depends on it.

**Comment by donkirkby** [comment]
When you say it no longer complains, do you mean that the live coding display works?

I was able to reproduce the problem, and it looks like there's something wrong with the call to `python.exe`. It's weird, because trying the same command on the command prompt works. I'll keep digging.

**Comment by liurui39660** [comment]
It "works" as this issue indicates.

I have no idea why the call failed. My case is, I only have one python installed, using conda, and its path is within the system-wide `%PATH%`.
