### ISSUE TITLE
Don't display full list for list item assignment

### ISSUE THREAD

**Issue by guyomes** [donkirkby/live-py-plugin#31]
In the following code:

~~~~
L = ['a','long','list'] 
for i in range(len(L)):
    L[i] = L[i] + ' very' 
~~~~

the full list is displayed in each column of the for loop, whereas displaying only the assigned item seems more appropriate.

**Comment by donkirkby** [comment]
I've closed this issue with a fix, and I'll try it out for a while. I actually like all the other changes that came with it, so I'll probably leave it this way.

**Comment by guyomes** [comment]
Thanks for the change !
I just tried it and I got the error
~~~
AttributeError: 'Name' object has no attribute 'n'
~~~
whith the example :
~~~
L = ['a','long','list'] 
for i in range(len(L)):
    L[i] = L[i] + ' very' 
~~~

I tracked the error at line 36 of the file `code_tracer.py`. Using the attribute `id` instead of `n` it shows the string `i` but it would be great if it showed the actual value of `i`.

**Comment by donkirkby** [comment]
That's embarrassing, I didn't test it with the original code you posted. I'll fix it up.
