### ISSUE TITLE
pycharm plugin failed to start

### ISSUE THREAD

**Issue by freephys** [donkirkby/live-py-plugin#319]
## What I did
Describe the steps you took, probably including your Python code, like this:

```
on ubuntu, install latest pycharm community and pluin from market place. But failed when starting live coding with messages below. Wonder what version/p[latform that the pluin has been tested to be workin ? 
```

## What happened
Describe what you saw, probably including the live coding display, like this:

Live coding plugin error:
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f1b60416740 (most recent call first):

```
print('42') 
```

## What I wanted to happen
Describe what you wanted, probably including changes to the live coding display, like this:

```
print('What do you get when you multiply six by nine?') 
```

## My environment
Describe the versions of everything you were using:
* Editor (PyCharm, Emacs, or SublimeText)
* Live Coding plugin
* Operating system
* Python

## Other feedback
While you're here, we'd love to know how you learned about the project, what you use it for, or anything else you'd like to tell us.

**Comment by freephys** [comment]
BTW, I am using the python virtualenv. Please help thanks

**Comment by donkirkby** [comment]
Thanks for the bug report. Can you please fill in the version numbers in the **My Environment** section?

The error message looks like there might be something wrong with your Python. Does your script work when you run it normally in PyCharm, not in live-coding mode?

To answer your question, I'm currently running PyCharm 2021.2.2 (Professional Edition) on Ubuntu 20.04 with Python 3.9.7 and Live Coding 4.4.0. When you tell me what you're using, I'll do my best to reproduce it.

**Comment by donkirkby** [comment]
No response for two months, so I'm going to close this issue. Feel free to add more information any time, and I'll reopen it.
