### ISSUE TITLE
Feature request: Support for Python from WSL

### ISSUE THREAD

**Issue by foldvari** [donkirkby/live-py-plugin#321]
## What I did
Describe the steps you took, probably including your Python code, like this:

```
I attempted to start live coding using Python interpreter  from WSL
```

## What happened
Describe what you saw, probably including the live coding display, like this:

```
I got the below exception:
Live coding plugin exception:
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\\wsl$\Ubuntu-20.04\usr\bin\python" (in directory "C:\Users\xxxxx\AppData\Roaming\JetBrains\PyCharm2021.2\scratches"): CreateProcess error=1921, The name of the file cannot be resolved by the system
```

## What I wanted to happen
Describe what you wanted, probably including changes to the live coding display, like this:

```
Live Coding works with Python in WSL.
```

## My environment
Describe the versions of everything you were using:
* PyCharm2021.2 Professional
* Live Coding plugin
* Windows + Ubuntu 20.04 running in WSL
* Python 3.8

**Comment by donkirkby** [comment]
I recreated the problem, and I've been digging through the IDEA source code to see if I can support WSL interpreters.

It looks like the [PythonRunner class] knows how to launch a WSL interpreter, but I haven't figured out how to pass it everything it needs. Maybe I can pass the command line patcher to the PythonRunner?

[PythonRunner class]: https://github.com/JetBrains/intellij-community/blob/c6083a07dfc109fa0aab164455b014dea724c5de/python/src/com/jetbrains/python/run/PythonRunner.java#L58

**Comment by donkirkby** [comment]
I posted a [question] about how to tweak the run configuration, to see if there's a more flexible way than I'm currently using.

I found it was useful to trace subprocesses in [`BaseProcessHandler`].

[question]: https://intellij-support.jetbrains.com/hc/en-us/community/posts/10703384188946-Adjust-run-configuration-in-a-plugin
[`BaseProcessHandler`]: https://github.com/JetBrains/intellij-community/blob/1747ca23053008a462d23874bd38c9a6ac7352a7/platform/util/src/com/intellij/execution/process/BaseProcessHandler.java#L30

**Comment by donkirkby** [comment]
After looking at how the PythonRunner class launches a WSL interpreter, I can't see any way to extend that class or use their code. It's too much code for me to reimplement, so I'm not going to support WSL interpreters. If I ever get an answer to my question or the PythonRunner class adds some extension points I can use, I'll reopen this issue.
