### ISSUE TITLE
Simple turtle methods

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#350]
There are a few turtle methods that aren't implemented by `MockTurtle`:

* [x] `filling()`
* [x] `getturtle()` and `getpen()`
* [x] `clone()`

Read the documentation for the standard methods and implement them.

**Comment by yonMaor** [comment]
Hey, can you eleborate further on this issue?
I might be able to help here

**Comment by donkirkby** [comment]
Sure, @yonMaor, thanks for your interest in helping out. A collaborator recently went through all the methods described in the [turtle module](https://docs.python.org/3/library/turtle.html#turtle.filling), and sent me a list of the ones that we haven't implemented yet. These three look like the simplest to start with.

Follow that link and read the description of what they're supposed to do, then take a look at the `MockTurtle` [source code](https://github.com/donkirkby/live-py-plugin/blob/master/plugin/PySrc/space_tracer/mock_turtle.py) to decide how to implement them.

To test out your idea, follow the instructions in the `CONTRIBUTING.md` file in the root directory for PyCharm development. Let me know if you need any more guidance.

**Comment by donkirkby** [comment]
Good news, the fix for #353 also fixed part of this issue. `filling()` is still missing, though.

**Comment by donkirkby** [comment]
Sorry to steal this issue from you, @yonMaor, but the `filling()` fix came for free when I removed a bunch of overrides for #353 in commit 2b61e97acddfcb67ff749d733cf259759ba24d91.

If you're still interested, #348 is a good one to start on.
