### ISSUE TITLE
Turtle colormode bug

### ISSUE THREAD

**Issue by BTWS2** [donkirkby/live-py-plugin#429]
## What I did
I tested the colormode online (https://donkirkby.github.io/live-py-plugin/demo/), but the color didn't change.

```python
import turtle as t

t.getscreen().colormode(255)
t.pensize(5)
t.color(0, 127, 255)
t.fd(200)

t.mainloop()
```

## What happened
The line is still black.

![image](https://user-images.githubusercontent.com/56451049/152877251-48497e4d-3f10-418b-94d6-52e70dc6358c.png)

## What I wanted to happen
The line should be blue.

```python
import turtle as t

# t.getscreen().colormode(255)
t.pensize(5)
t.color(0, 127/255, 255/255) # colormode(255) simulated
t.fd(200)

t.mainloop()
```
![image](https://user-images.githubusercontent.com/56451049/152877544-c8861f38-1c21-43bb-a22e-56fff7c618bd.png)

## My environment
* https://donkirkby.github.io/live-py-plugin/demo/

**Comment by donkirkby** [comment]
This was fixed in #352, but I hadn't deployed version 4.8.0 yet. It's now deployed, so you should see the fix in the browser.
