### ISSUE TITLE
Issue with laptop 

### ISSUE THREAD

**Issue by sghazi1** [donkirkby/live-py-plugin#432]
## What I did
Describe the steps you took, probably including your Python code, like this:
Computer stopped working - had the blue screen on 'your pc ran into a problem'
I tried pressing the home button for 60 seconds and it turned back on.
```
print(42)
```

## What happened
Describe what you saw, probably including the live coding display, like this:

```
print('42') 
```

## What I wanted to happen
Describe what you wanted, probably including changes to the live coding display, like this:

```
print('What do you get when you multiply six by nine?') 
```

## My environment
Describe the versions of everything you were using:
* Editor (PyCharm, Emacs, or SublimeText)
* Live Coding plugin
* Operating system
* Python

## Other feedback
While you're here, we'd love to know how you learned about the project, what you use it for, or anything else you'd like to tell us.

**Comment by donkirkby** [comment]
It's very unlikely that Python code would crash your computer. However, if you can reproduce the problem, please fill in the information we asked for above.
