### ISSUE TITLE
Isn't there a way to put the live coding screen to the left in Intellij?

### ISSUE THREAD

**Issue by qkrtkdwns3410** [donkirkby/live-py-plugin#485]
I couldn't find your email address, so I put it on the issue.

**Comment by donkirkby** [comment]
I've never thought of that as an option. Is there a reason that would be better?

If anyone wants to work on it, the window layout is handled [here].

[here]: https://github.com/donkirkby/live-py-plugin/blob/v4.8.1/pycharm/src/io/github/donkirkby/livepycharm/SplitFileEditor.java#L447-L452

**Comment by qkrtkdwns3410** [comment]
Since the video of my sub-monitor lecture is located on the right side, it is convenient to put the live coding screen on the left side to relax the eyes of the screen. I hope it is provided as a separate option. I have never contributed to the plug-in, so I cannot add a separate option. Can I change the left and right sides of the plug-in screen separately and use it separately?

**Comment by qkrtkdwns3410** [comment]
just add 
splitter.swapComponents();
`            
        final JPanel result = new JPanel(new BorderLayout());
        splitter.swapComponents();
        result.add(splitter, BorderLayout.CENTER);
        adjustEditorsVisibility();
`

show live screen left .. i just wanna add swap function but i could not..
