### ISSUE TITLE
Spinoff live-py emacs mode into MELPA package?

### ISSUE THREAD

**Issue by cpaulik** [donkirkby/live-py-plugin#50]
Hi,

Thank you for writing this plugin and making it usable in emacs.

Would you be open to setting it up so that [MELPA](http://melpa.org/) can pick it up?
I think I could help since I have some experience in setting up a MELPA package.

**Comment by donkirkby** [comment]
Glad you like the project, the Emacs support was actually contributed by @akaihola. I love Emacs, but I haven't used it in years. If you're willing to contribute the package configuration, I will happily test it out and merge it.

**Comment by cpaulik** [comment]
After the `live-py-mode.el` has the correct format I will submit a PR to MELPA with the recipe for building the package.

**Comment by donkirkby** [comment]
I have merged your changes into `master`, and I created a new branch called `melpa`. Please use the `melpa` branch in the MELPA build recipe. That way, I can do my development work on `master`, then push to `melpa` when I want to release.

**Comment by cpaulik** [comment]
When this https://github.com/milkypostman/melpa/pull/3261 closes then the package should be available soon after.

**Comment by purcell** [comment]
MELPA packages always target the current development version, so we want to track `master`. That said, if you tag the code with version numbers, stable release packages will be built in MELPA Stable. So @cpaulik, you should please remove the `:branch` spec from the recipe in the MELPA PR.

**Comment by donkirkby** [comment]
Just to be clear, when I commit to `master` in my project, MELPA will pull it and build it into MELPA's development version. When I create a GitHub release with a git tag like "v1.1", then MELPA will pull it and build it into MELPA's stable version. Is that right?
If so, then I'm fine with that.

**Comment by purcell** [comment]
Yep, that's exactly right.

**Comment by donkirkby** [comment]
I tested out the installation from MELPA, and it worked fine. `melpa-stable` doesn't work, but that's because the Emacs mode in the last release wasn't compatible with MELPA. Next release should work in `melpa-stable`.
