### ISSUE TITLE
Exception in plugin Live Coding in Python (2.25.1)

### ISSUE THREAD

**Issue by wni5378** [donkirkby/live-py-plugin#504]
## What I did
Describe the steps you took, probably including your Python code, like this:

```
- I installed the plugin in PHPStorm;
- I opened a Python file and the error occured;

```

## What happened
Describe what you saw, probably including the live coding display, like this:

```
- PHPStorm displayed an error and because the plugin is not a product of Jetbrains, I was unable to submit the report. Here is the contents of 
```

## What I wanted to happen
Describe what you wanted, probably including changes to the live coding display, like this:

```
**What do you get when you multiply six by nine?** That would be 54

Please see the attached files for errors and stacktrace (induced.txt and stacktrace.txt)
```

## My environment
Describe the versions of everything you were using:

* Editor: 
JetBrains PHPStorm 
Version 2022.2.3
Build #PS-222.4345.15, built on October 5, 2022

* Live Coding plugin:
Live Coding in Python 2.25.1

* Operating system:
Edition: Windows 10 Pro
Version: 22H2
Installed on: 2022-‎09-‎22 ‎Thu
OS build: 19045.2311
Experience: Windows Feature Experience Pack 120.2212.4190.0

* Python

## Other feedback

While you're here, we'd love to know how you learned about the project, what you use it for, or anything else you'd like to tell us.

I just wanted something similar to Python Intellisense to assist with Python development.

[induced.txt](https://github.com/donkirkby/live-py-plugin/files/10099763/induced.txt)
[stacktrace.txt.txt](https://github.com/donkirkby/live-py-plugin/files/10099764/stacktrace.txt.txt)

**Comment by donkirkby** [comment]
Thanks for the bug report. It looks like the compatibility information is wrong, and none of the new versions are marked as compatible with PHPStorm. I haven't tried it, so the newer versions may or may not actually work with PHPStorm. The old version that it suggests definitely won't work, though.

Suggestion: try downloading the plugin jar from its [plugin page], and then install it [from disk] in PHPStorm. Let me know if it works.

I'll see if I can figure out how to mark that old plugin version as incompatible with new versions of PHPStorm.

**Comment by wni5378** [comment]
Thanks for the response Don.

I will try your suggestions when I get home from work this evening and let you know what happens.

Have a good one.

**Comment by donkirkby** [comment]
I updated the version compatibility on all the old versions of the IDEA plugin, so it shouldn't be offered when it won't work.

Did downloading the plugin and installing from disk work for PHPStorm?

**Comment by donkirkby** [comment]
I'm going to assume that no news is good news, and close this issue. Feel free to add another comment if you're still having problems, and I'll reopen it.
