### ISSUE TITLE
Printing multiline datastructures

### ISSUE THREAD

**Issue by endrebak** [donkirkby/live-py-plugin#51]
I am using `live-coding` to view stuff like pandas dataframes.

`df = pd.DataFrame(range(10), index=reversed(range(10)))`

becomes `df =  0 9 0 8 1 7 2 6 3 5 4 4 5 3 6 2 7 1 8 0 9`.

Sometimes, I'd really like to see the datastructure like it would be printed, perhaps that could be done by sending some parts to a different buffer?

I dunno if using a comment symbol afterwards could denote datastructures that should be printed like they would be with print?

Like 

```python
df = pd.DataFrame(range(10), index=reversed(range(10))) 
dft = df.head(2) #=>
```

Sends the datastructure to a different buffer to be printed.

Another alternative would be to add a second mode, one that did not care about lines matching up, but just printed stuff over several lines.

**Comment by donkirkby** [comment]
Thanks for the suggestion. Some day, I might change the display so that it can expand and push open gaps in the code, but that won't happen any time soon. For now, I'm going to close this.
