### ISSUE TITLE
Avoid goto-line compiler warning in Emacs

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#56]
When using the new MELPA package installation, you get a warning.

```
`goto-line' used from Lisp code
```

Try to avoid the warning using one of the techniques described on [this question](http://stackoverflow.com/a/11805882/4794).

**Comment by brandm** [comment]
I just realized that this is currently the last open bug in the records: Well done.

Thanks for the suggestion to look into this and for catching the compiler warning as it potentially also affects the performance of `live-py-synchronize-scroll`. `goto-line` is an Emacs Lisp function and does quite some stuff before calling `forward-line`. `forward-line` is a C function and is now used solely in #107

**Comment by donkirkby** [comment]
Thanks for all your help, @brandm. It's nice to be bug free (for now).
