### ISSUE TITLE
PyCharm: IDE error: Exception in plugin Live Coding

### ISSUE THREAD

**Issue by fipachu** [donkirkby/live-py-plugin#577]
## What I did
I launched PyCharm, went to plugin marketplace, found Live coding, clicked 'Install', 'Apply', 'OK'.

## What happened
I got an IDE error notification. I clicked on it, this is what showed up:
<details><summary>Screenshot</summary>
<p>

![image](https://github.com/donkirkby/live-py-plugin/assets/80906036/f325f907-fe6c-481b-87de-a5ef0fd9c0b8)

</p>
</details>

<details><summary>Logs</summary>
<p>

[stacktrace.txt](https://github.com/donkirkby/live-py-plugin/files/13404286/stacktrace.txt)
[threadDump.txt](https://github.com/donkirkby/live-py-plugin/files/13404287/threadDump.txt)

</p>
</details>  

## What I wanted to happen
I just wanted to use the extension. It probably shouldn't do that.

## My environment
* PyCharm 2023.2.5 (Professional Edition)
* Live Coding plugin 4.11
* Windows 11, version 22H2
* Python 3.12.0

## Other feedback
The plugin seemed to work as it's supposed to with file test.py, even without restarting PyCharm. File turtle_demo.py however displayed "No turtle or matplotlib commands found[...]". After restarting IDE plugin seems to work ok with both files. No more IDE errors appear.

<details><summary>test.py</summary>
<p>

```python
s = 'Hello, '
s += 'World!'
``` 

</p>
</details> 

<details><summary>turtle_demo.py</summary>
<p>

```python
from turtle import *


def square():
    for i in range(4):
        forward(100)
        right(90)


def star():
    sides = 5
    distance = 200
    begin_fill()
    for _ in range(sides):
        forward(distance)
        right(2 * 360 / sides)

    end_fill()
    mainloop()


def spiral():
    sides = 5
    distance = 50
    color('black', 'green')
    begin_fill()
    for _ in range(50 * sides):
        forward(distance)
        right(2 * 360 / sides - 1)
        distance += 5

    end_fill()
    mainloop()


def main():
    square()
    # star()
    # spiral()


main()
``` 

</p>
</details>

**Comment by donkirkby** [comment]
That looks similar to #580, so I'm going to close this issue. Thanks for reporting it.
