### ISSUE TITLE
"zsh:1: command not found: python" error

### ISSUE THREAD

**Issue by notUserX** [donkirkby/live-py-plugin#609]
## What I did
Launched Emacs. Opened .py file. `M-x live-py-mode`

## What happened

```(zsh:1: command not found: python)```

## What I wanted to happen
I wanted to visualize my code instantly.

## My environment
* GNU Emacs 29.1 (build 1, aarch64-apple-darwin23.3.0, Carbon Version 170 AppKit 2487.4) of 2024-03-01
* Installing live-py-mode via github repo "donkirkby/live-py-plugin"
* Operating system: 14.4 (23E214)
* Python: /Users/<...>/.pyenv/shims/python
  with global version set to 3.10.2

## Other feedback
I was searching for REPL options in Emacs and stumbled upon your project.

**Comment by donkirkby** [comment]
The error message says that you don't have a `python` command in your path, so you have two options:

1. Set the Python version with `C-c M-v`. You probably want to use `python3` or `python3.10`. Try `C-h m` and scroll down to the live-py mode section to see all the options you can configure.
2. Activate a Python virtual environment before you launch Emacs. That will put a `python` command in your path.

If that doesn't work, you can reopen this issue and add the details of what's going wrong.

**Comment by notUserX** [comment]
Thanks for your reply.

`C-c M-v <ret> python3 <ret>` solves my problem. 

After this, `C-h v` shows that my `live-py-version` is set to "/opt/homebrew/bin/python3"

However, with the following in my .init file
`(defun my-live-py-mode-hook ()
  "Hook function to set live-py-version."
  (setq live-py-version "/opt/homebrew/bin/python3"))

(add-hook 'live-py-mode-hook 'my-live-py-mode-hook)
`
`C-h v` also shows that my `live-py-version` is set to "/opt/homebrew/bin/python3", yet `M-x live-py-mode` generates the `(zsh:1: command not found: python)` error.

I would have thought that it would not matter how `live-py-version` is set, but apparently, it does.
