### ISSUE TITLE
PyCharm plugin

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#95]
Learn how to write a [PyCharm plugin], and choose some minimal version of the live coding to start with.

* [x] hello world plugin
* [x] side-by-side display window (always visible?)
* [ ] show live coding display

[PyCharm plugin]: http://www.jetbrains.org/intellij/sdk/docs/basics.html

**Comment by donkirkby** [comment]
The [live-plugin] project might be a good way to prototype a plugin.

[live-plugin]: https://github.com/dkandalov/live-plugin

**Comment by donkirkby** [comment]
See if there are useful hints in [CodeGlance].

[CodeGlance]: https://github.com/Vektah/CodeGlance

**Comment by donkirkby** [comment]
Maybe the [markdown plugin][md] will give hints on how to add a splitter to the editor.

[md]: https://github.com/JetBrains/intellij-plugins/tree/master/markdown

**Comment by donkirkby** [comment]
Could the [InlayModel] be a useful way to display things next to the source code?

[InlayModel]: https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/openapi/editor/textarea/TextComponentInlayModel.java

**Comment by simonhughes22** [comment]
@donkirkby - I would love to use this in PyCharm. Is there a way I can do this right now? Are you planning on publishing this as a PyCharm plugin? I can't see it in the plugins repo right now, but it looks like you just started working on this.

**Comment by donkirkby** [comment]
I've only implemented a minimal version, @simonhughes22, and I haven't published it to the PyCharm plugin directory yet. If you really wanted to try it out, you could run it from [source code], or you could try the Eclipse or Emacs versions. If you just want to learn more about how it works, there are links to a demo video and the getting started page on the [project page].

[source code]: https://github.com/donkirkby/live-py-plugin/blob/master/CONTRIBUTING.md#pycharm-development
[project page]: http://donkirkby.github.io/live-py-plugin/
