### ISSUE TITLE
Use of `yield` breaks live preview in Emacs

### ISSUE THREAD

**Issue by teodorlu** [donkirkby/live-py-plugin#96]
Hello,

I'm having issues with functions using the yield keyword, like in this file:

```python
def numbers():
    yield 1
    yield 2
    yield 3
    return

def main():
    for n in numbers():
        print n
main()
```

When running this file with live-py in Emacs, I'm getting an error: `SyntaxError: 'return' with argument inside generator (<live coding source>, line 4) `. Running the file in the command line prints 1, 2 and 3.

**Comment by donkirkby** [comment]
Thanks for the interesting bug report, I should be able to fix it tonight. It looks like I'm converting the `return` to a `return None` when I instrument the code. Are you using the stable Emacs package, or the regular one?

If you need a workaround, you can just raise a `StopIteration()` exception. That should have exactly the same result as a `return` statement in a generator function.

    def numbers():            | 
        yield 1               | yield 1 
        yield 2               | yield 2 
        yield 3               | yield 3 
        raise StopIteration() | StopIteration 
                              | 
    def main():               | 
        for n in numbers():   | n = 1   | n = 2   | n = 3 
            print n           | print 1 | print 2 | print 3 
    main()                    |

**Comment by teodorlu** [comment]
Thanks for the prompt fix!

I'm using the one that comes with Spacemacs' Python layer. I found this line in my config directory:
```
./elpa/live-py-mode-20161125.2208
```

Honestly, the entire experience was surprising. I'm new to Emacs, so I'm messing around with all the things I can do, trying the ones that sound interesting. And I suddenly find this `live-py-mode`. Hmm, let's check it out. And it's really live coding. And it works well!

Thanks for making Python programming 42 % more fun :)

**Comment by donkirkby** [comment]
That doesn't look like a stable release, so you should be able to update your packages now to get the fix.
